### ISSUE TITLE
Mac Build 失败

### ISSUE THREAD

**Issue by vencewill** [PinkD/corplink-rs#21]
Chip：Apple M1 Pro
macOS：14.2.1 (23C71)

Backtrace：
```bash
error: failed to run custom build command for `corplink-rs v0.4.1 (~/Developer/corplink-rs)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `~/Developer/corplink-rs/target/release/build/corplink-rs-d418f6c1350adc9d/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-search=./libwg
  cargo:rustc-link-lib=wg
  cargo:rerun-if-changed=./libwg/libwg.h
  cargo:rerun-if-env-changed=TARGET
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64-apple-darwin
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64_apple_darwin
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS

  --- stderr
  thread 'main' panicked at build.rs:48:10:
  Unable to generate bindings: NotExist("./libwg/libwg.h")
  stack backtrace:
     0:        0x1013cffb0 - std::backtrace_rs::backtrace::libunwind::trace::h815672f5996c9e34
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:        0x1013cffb0 - std::backtrace_rs::backtrace::trace_unsynchronized::h2e094b2d8c270437
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:        0x1013cffb0 - std::sys_common::backtrace::_print_fmt::hae24b71afea95695
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
     3:        0x1013cffb0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6d4268b2ed62fb94
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
     4:        0x1013edadc - core::fmt::rt::Argument::fmt::h835101b6de0df17f
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
     5:        0x1013edadc - core::fmt::write::h5d55d44549819258
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
     6:        0x1013cd0bc - std::io::Write::write_fmt::hc515897f91abd6cf
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
     7:        0x1013cfdf0 - std::sys_common::backtrace::_print::h5844dab5cfa39fca
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
     8:        0x1013cfdf0 - std::sys_common::backtrace::print::h2c300c1ebedfc73c
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
     9:        0x1013d1450 - std::panicking::default_hook::{{closure}}::h0aa9be5c44269370
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
    10:        0x1013d117c - std::panicking::default_hook::h2c0ef097934ee9e6
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
    11:        0x1013d1998 - std::panicking::rust_panic_with_hook::h84c8637cb6e56008
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
    12:        0x1013d18a4 - std::panicking::begin_panic_handler::{{closure}}::h25482adda06c7b7f
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:599:13
    13:        0x1013d043c - std::sys_common::backtrace::__rust_end_short_backtrace::h0c6f3beb22324a29
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
    14:        0x1013d1608 - rust_begin_unwind
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
    15:        0x10140019c - core::panicking::panic_fmt::h9072a0246ecafd14
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
    16:        0x1014004c4 - core::result::unwrap_failed::hd7600d03a3086be4
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
    17:        0x100ee6cb8 - core::result::Result<T,E>::expect::ha108bc8607a3fd47
    18:        0x100ee7a14 - build_script_build::main::h58525d79c64b1485
    19:        0x100ee677c - core::ops::function::FnOnce::call_once::hde7dee7b1fe19b97
    20:        0x100ee5e68 - std::sys_common::backtrace::__rust_begin_short_backtrace::h78dc25431d1891e0
    21:        0x100ee64c8 - std::rt::lang_start::{{closure}}::h436e1e09b3b81bbb
    22:        0x1013c8ea4 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7fff7c88c61df16f
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:284:13
    23:        0x1013c8ea4 - std::panicking::try::do_call::h5c3526811781b4da
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
    24:        0x1013c8ea4 - std::panicking::try::h64cb573047f67390
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
    25:        0x1013c8ea4 - std::panic::catch_unwind::h0ee316aa6f14634c
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
    26:        0x1013c8ea4 - std::rt::lang_start_internal::{{closure}}::hbd896cc316ba7338
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:48
    27:        0x1013c8ea4 - std::panicking::try::do_call::hbae6886803fae47e
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
    28:        0x1013c8ea4 - std::panicking::try::hcc0fbb3995231d31
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
    29:        0x1013c8ea4 - std::panic::catch_unwind::hf36acbaf210582be
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
    30:        0x1013c8ea4 - std::rt::lang_start_internal::hadaf077a6dd0140b
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:20
    31:        0x100ee64a4 - std::rt::lang_start::hebcad678217747b4
    32:        0x100ee7bac - _main
```

master clone 下来的找不到 `./libwg/libwg.h`

**Comment by PinkD** [comment]
1. 修改 `libwg/build.sh` ，去掉其中的 `--depth=1` 选项。该选项会导致生成 `version.go` 失败，具体参考 `Makefile`
2. 运行 `build.sh` ，编译 `libwg`
3. `cargo build`

**Comment by vencewill** [comment]
感谢解答，分步执行`build.sh`成功了
